name: CI

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*' ]
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Test (${{ matrix.os }} / py${{ matrix.python-version }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      - name: Set up conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: test-env
          python-version: ${{ matrix.python-version }}
          auto-update-conda: true
          channels: conda-forge
          channel-priority: strict

      - name: Install dependencies
        shell: bash -l {0}
        run: |
          conda install -y -c conda-forge scikit-sparse
          conda install -y -c conda-forge eigenpy
          conda install -y -c conda-forge pydiso
          python -m pip install -U pip
          python -m pip install qdldl pytest
          python -m pip install -e .[test] || python -m pip install -e .

      - name: Run tests
        shell: bash -l {0}
        run: |
          pytest -s
          # Run one test verbose to see logging.
          pytest -s tests/test_qtqp.py::test_solve[LinearSolver.SCIPY-seed0-True]

  build-and-publish:
    if: startsWith(github.ref, 'refs/tags/')
    needs: [test]
    name: Build & Publish to PyPI
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: "3.11"
          cache: pip

      - name: Build sdist and wheel
        run: |
          python -m pip install -U pip build
          python -m build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/*

      - name: Publish to PyPI (Trusted Publishing)
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          print-hash: true
          # repository-url: https://test.pypi.org/legacy/
          # skip-existing: true

